### ISSUE TITLE
Wrong dump values with one touch select plus and food information

### ISSUE THREAD

**Issue by lnykryn** [Flameeyes/glucometerutils#22]
When I don't mark the measurement with the information about food, everything is fine. When I mark it after/before food, the value is wrong.

[lnykryn@old ~]$ sudo glucometer.py --driver otverio2015 --device /dev/sg1 dump | tail -5
"2017-09-12 11:38:02","3644.00","","" (should be 3.1 (before food))
"2017-09-12 13:33:07","7288.94","","" (should be 7.2 (after food))
"2017-09-12 18:04:30","3646.11","","" (should be 5.2 (before food))
"2017-09-12 20:06:58","7289.78","","" (should be 8.0 (after food))
"2017-09-12 23:06:58","4.28","",""       (is fine (no mark))

**Comment by Flameeyes** [comment]
Thank you for reporting this! Looks like I misinterpreted the record format, and this should be fixed in the master branch. Can you test this after pulling? It should not only show the right values, but also know the before/after meal flag values.

**Comment by lnykryn** [comment]
Looks like the current code ends with a traceback in my case:
[lnykryn@notas ~]$ sudo glucometer.py --driver otverio2015 --device /dev/sg1 dump 
Traceback (most recent call last):
  File "/bin/glucometer.py", line 142, in <module>
    main()
  File "/bin/glucometer.py", line 104, in main
    readings, key=lambda reading: getattr(reading, args.sort_by))
  File "/usr/lib/python3.5/site-packages/glucometerutils/drivers/otverio2015.py", line 273, in get_readings
    yield self._get_reading(record_number)
  File "/usr/lib/python3.5/site-packages/glucometerutils/drivers/otverio2015.py", line 268, in _get_reading
    _convert_timestamp(timestamp), float(value), meal=_MEAL_CODES[meal_flag])
KeyError: 2

and here it is with debug output:
[lnykryn@notas ~]$ sudo glucometer.py --driver otverio2015 --device /dev/sg1 --vlog 0 dump 
DEBUG:root:Sending packet: b'020a0004e6020103910a'
DEBUG:root:Read packet: b'04064f006e00650054006f007500630068002000530065006c00650063007400200050006c00750073000000'
DEBUG:root:Sending packet: b'020a0004e6020003a039'
DEBUG:root:Read packet: b'0406450041004a00500042003100580035000000'
DEBUG:root:Sending packet: b'020a0004e6020203c25f'
DEBUG:root:Read packet: b'040651005500340030003100300030005f003000310031000000'
DEBUG:root:Sending packet: b'0208000404031aa7'
DEBUG:root:Read packet: b'030601000000'
DEBUG:root:Sending packet: b'020900042700030b20'
DEBUG:root:Read packet: b'04069100'
DEBUG:root:Sending packet: b'020c0004310200000003a955'
DEBUG:root:Read packet: b'04060000009d00ade74b21850002004c0b00'
Traceback (most recent call last):
  File "/bin/glucometer.py", line 142, in <module>
    main()
  File "/bin/glucometer.py", line 104, in main
    readings, key=lambda reading: getattr(reading, args.sort_by))
  File "/usr/lib/python3.5/site-packages/glucometerutils/drivers/otverio2015.py", line 273, in get_readings
    yield self._get_reading(record_number)
  File "/usr/lib/python3.5/site-packages/glucometerutils/drivers/otverio2015.py", line 268, in _get_reading
    _convert_timestamp(timestamp), float(value), meal=_MEAL_CODES[meal_flag])
KeyError: 2

**Comment by Flameeyes** [comment]
Hah there goes me trying to fix this without the device at hand :) Should be good now.

(I don't have my Verio 2015 meters at hand right now, as they are packed up already :/)

**Comment by lnykryn** [comment]
Damn you are fast. I was just about to send you the same patch :-). Current code works for me. Thanks!
