### ISSUE TITLE
'ascii' encoding error

### ISSUE THREAD

**Issue by achanhon** [Flameeyes/glucometerutils#60]
I have a strange encoding error when using glucmeterutils for a freestylelibre.

here the log:

sudo -E glucometer --driver ${DRIVER} info
Traceback (most recent call last):
  File "/usr/local/bin/glucometer", line 9, in <module>
    load_entry_point('glucometerutils==1', 'console_scripts', 'glucometer')()
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/glucometer.py", line 89, in main
    device_info = device.get_meter_info()
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/drivers/fslibre.py", line 213, in get_meter_info
    patient_name=self.get_patient_name())
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/support/freestyle.py", line 191, in get_patient_name
    patient_name = self._send_text_command(b'$ptname?').rstrip('\r\n')
  File "/usr/local/lib/python3.5/dist-packages/glucometerutils/support/freestyle.py", line 159, in _send_text_command
    full_content += content.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

I have tested many many kind of "export LC_ALL=UTF-8" but I found nothing to bypass the problem... 
tested on Ubuntu 16.04 with a standard python3

Thank for your github

**Comment by Flameeyes** [comment]
Ah, I think I know what's going on there, I had explicitly not tried to use my proper surname in there as I expected it not to accept non-ascii characters.

I'll either have to try configuring it with Windows and see what I get out there, or if you don't mind sharing your name and the output of `--vlog=4`, I can take it from there. I _expect_ the Libre will use Latin-1 encoding for patient names, rather than UTF-8, but who knows.

**Comment by achanhon** [comment]
Thank for the support, I will try and I let you know.

**Comment by Flameeyes** [comment]
This _should_ be working now, although you probably will see the "wrong" patient name there.

AFAICT the Windows app does not validate patient name at all, and I only get the 0xc3 byte in there.

**Comment by achanhon** [comment]
I confirm that it work now. 

Thank. Sorry for the delay... 

Cordially. 

Adrien 

Le 2019-07-30 18:49, Diego Elio Pettenò a écrit : 

> Closed #60 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

  

Links:
------
[1] https://github.com/Flameeyes/glucometerutils/issues/60
[2]
https://github.com/Flameeyes/glucometerutils/issues/60?email_source=notifications&amp;email_token=AG3GGFRJXQXBNFAZUAWPIGDQCBWJBA5CNFSM4IEUFGRKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSY5Z7TQ#event-2520489934
[3]
