### ISSUE TITLE
Ascensia and Bayer Contour device drivers  

### ISSUE THREAD

**Issue by arvchristos** [Flameeyes/glucometerutils#61]
Hello and thanks for the hard effort so far. I need a couple of days to finish the first version of ContourUSB by Bayer driver and format the code to be readable and conforming to glucometerutils styling principles. 

During development, I found out that Ascensia provides protocol documentation for almost all of her glucose meters, so no reverse engineering is needed. The documentation can be found [here](http://protocols.ascensia.com/Programming-Guide.aspx).

Having only a ContourUSB meter available, I post this issue in hope of finding developers that have any of the documented Ascensia meters and are willing to grab any implementation opening.

**Comment by Flameeyes** [comment]
Thank you for letting me know about this! It's an awesome thing from Ascensia indeed. I have a Next One as well as the ContourUSB so I'll take a look at the Next protocol and implement that one once I have some time (I had to take a partial break due to a wrist injury).

**Comment by arvchristos** [comment]
@Flameeyes I think that there is no need to document the protocol in your relevant repository in my Contourusb push request. Am I correct ?

**Comment by Flameeyes** [comment]
Correct! Just add the link to their CIS page so that there's a quick reference to it for the future.

The LIS stuff, which @flupzor referenced there, is annoyingly closed, so that's not easy to reference, and at the same time risky to clear-room, but I might get myself a copy to keep at hand, if need be.

**Comment by mjsduncan** [comment]
the link at http://protocols.ascensia.com/Programming-Guide.aspx no longer exists, can anyone post a copy?

**Comment by steve8x8** [comment]
web.archive.org has a lot of copies, no need to duplicate your request ...
