### ISSUE TITLE
fslibre "dump" doesn't return

### ISSUE THREAD

**Issue by steve8x8** [Flameeyes/glucometerutils#63]
I've built glucometer for fslibre (reader s/n JCMX166-*, s/w version 2.2.13), and can run "info", "patient", "date time" requests which return sensible results - but as soon as I try to "dump", I get no results at all (or a checksum error, in rare cases).
Is there a means to find out what's going on?

**Comment by Flameeyes** [comment]
You should be able to get a debug log by using `./glucometer.py --vlog 5 --driver fslibre dump`.

My Libre has software version 2.1.2 (and cannot be updated for the new firmware), so it might be possible that they changed the protocol enough that it's not working with the current driver.

If you can attach the log (or send me by email if you prefer, as it might be too personal — flameeyes@flameeyes.com), I'll take a look and see what might be the issue.

**Comment by steve8x8** [comment]
Ah, I might have found out about `--vlog` myself (although I'm more familiar with Ruby than Python). I presume you'll need the first and last few lines only? [1st run](http://steve8x8.faehrwiese.selfhost.me/glucometer/run-cut1.out) [2nd run](http://steve8x8.faehrwiese.selfhost.me/glucometer/run-cut2.out) Full logs on request.

In the full logs, I see that starting with record 7663 there are differences in character counts in the "record tail" (consisting of `[\r\n\x00]*` - which may be irrelevant?). Record numbers seem to count down, wrapping up to 64k, but that's not causing any visible problems; to me it seems that some records get omitted though. Strange. I've got a Bluetooth mouse attached which is `/dev/hidraw0` - could it interfere with the `hidraw1` transmission?

**Comment by Flameeyes** [comment]
No the Bluetooth device shouldn't interfere at all… although it's interesting that in both logs it stops exactly at the same entry. Can you confirm this is always the case? Has it changed now, but always stopping at the same entry?

The record tail is normal — messages are encapsulated in 63-bytes packets, so only part of the length needs to be exported. Likely it's just a dirty buffer.

Could you see what happens if you use the the `reversing_tools/abbott/freestyle_hid_console.py` tool and type in `$history?` and `$results?` ? I have a feeling they may have subtly changed the protos to break tools like this one :/

**Comment by steve8x8** [comment]
1. I suppose the "Apr 8, 2019 22:41:13" record may be the first one (chronologically) that could still be stored. The device has been in use for a long time (not by me though) and there may have been several wrap-arounds. While the very last record is identical in both dumps, the one shown before is not. Is it normal that dump mode would "lose" records? (I suppose it wouldn't invent new ones, so the difference must have another reason.)
I've found widely differing counts of "type 60 content" lines - 8411 for the first, only 8297 for the second run. So some data must have been lost *in both*.
2. Shouldn't dirty buffers be identical too? In particular as this device hasn't been in use since Aug 20?
3. 
```
$ python3 -V
Python 3.5.3
$ ./freestyle_hid_console.py 
  File "./freestyle_hid_console.py", line 44
    print(f'>>> {command}')
                         ^
SyntaxError: invalid syntax
```
Of course, this is without the device connected - I'm at work and running the command remotely. Will redo the same when back home.

I'd greatly appreciate to be able to read out the measurement values from a single-sensor experiment which I'd like to start this coming weekend... right now, I've still got the option to NFC the Libre using my mobile, but there's a chance to break one of them... Thanks so far, I'll be back!

**Comment by steve8x8** [comment]
First, some more data. I ran the dump command 5 times, numbered 3~7, with a cable disconnect (but no power down) after run 4.
```
==> run3.out <==
DEBUG:root:Received message: type 60 content b'58012,12,4,8,19,22,56,13,1,0,0,0,0,191,3765,0\r\n'
DEBUG:root:Read packet: b"`'12572,01A4B897\r\nCKSM:01A4BB9B\r\nCMD OK\r\n95,0\r\n\r\n\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
DEBUG:root:Received message: type 60 content b'12572,01A4B897\r\nCKSM:01A4BB9B\r\nCMD OK\r\n'
Error while executing 'dump': Invalid response received:
Response checksum not matching: 01a4bb9b expected, 0106a70c received

==> run4.out <==
DEBUG:root:Received message: type 60 content b'58017,12,4,8,19,23,41,59,1,0,0,0,0,169,3810,0\r\n'
DEBUG:root:Read packet: b'`/58013,12,4,8,19,23,11,13,1,0,0,0,0,200,3780,0\r\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 60 content b'58013,12,4,8,19,23,11,13,1,0,0,0,0,200,3780,0\r\n'
DEBUG:root:Read packet: b'`/58011,12,4,8,19,22,41,13,1,0,0,0,0,175,3750,0\r\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 60 content b'58011,12,4,8,19,22,41,13,1,0,0,0,0,175,3750,0\r\n'

==> run5.out <==
DEBUG:root:Received message: type 60 content b'58012,12,4,8,19,22,56,13,1,0,0,0,0,191,3765,0\r\n'
DEBUG:root:Read packet: b"`'12572,01A4B897\r\nCKSM:01A4BB9B\r\nCMD OK\r\n95,0\r\n\r\n\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
DEBUG:root:Received message: type 60 content b'12572,01A4B897\r\nCKSM:01A4BB9B\r\nCMD OK\r\n'
Error while executing 'dump': Invalid response received:
Response checksum not matching: 01a4bb9b expected, 0123bdc1 received

==> run6.out <==
DEBUG:root:Received message: type 60 content b'58012,12,4,8,19,22,56,13,1,0,0,0,0,191,3765,0\r\n'
DEBUG:root:Read packet: b"`'12572,01A4B897\r\nCKSM:01A4BB9B\r\nCMD OK\r\n95,0\r\n\r\n\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
DEBUG:root:Received message: type 60 content b'12572,01A4B897\r\nCKSM:01A4BB9B\r\nCMD OK\r\n'
Error while executing 'dump': Invalid response received:
Response checksum not matching: 01a4bb9b expected, 011be294 received

==> run7.out <==
DEBUG:root:Received message: type 60 content b'58020,12,4,9,19,0,26,59,1,0,0,0,0,162,3855,0\r\n'
DEBUG:root:Read packet: b'`/58013,12,4,8,19,23,11,13,1,0,0,0,0,200,3780,0\r\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 60 content b'58013,12,4,8,19,23,11,13,1,0,0,0,0,200,3780,0\r\n'
DEBUG:root:Read packet: b'`/58011,12,4,8,19,22,41,13,1,0,0,0,0,175,3750,0\r\n\n\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
DEBUG:root:Received message: type 60 content b'58011,12,4,8,19,22,41,13,1,0,0,0,0,175,3750,0\r\n'
```
If the last received record is 58011, the program hangs. If it's 58012, a checksum error is reported. In any case, many records are skipped.

**Comment by steve8x8** [comment]
BTW I seem to be unable to get the usage of the reversing tools right. Even when Iäm not redirecting stdin, the f'>>>{command} error is raised. Debian Stretch, bash.

**Comment by steve8x8** [comment]
I have disabled the checksum test now, and am getting "down" to record 58012 or 58011, provided the read doesn't hang (I've disabled --vlog=5 not to be flooded anymore, since the pattern is clear - it takes a dozen attempts to get one or two sets of data). Block-wise output has some disadvantages, but I understand that's caused by the "object oriented" approach (the whole response gets analyzed - if it ever becomes whole).

Okay, since 58011 seems to be the last recond indeed I'm not missing anything important anymore, I can just try to fill the gaps to get a data set as complete as possible.

Still the question remains why 
 - records are missing (= are not sent by the device? but taken into account for checksums I presume)
- counting down to 58012 succeeds (in a sense, i.e. it finishes)
- counting down to 58011 happens but the communication hangs thereafter

I'm afraid I cannot help with this one any further.

**Comment by Flameeyes** [comment]
Hrm, it does sounds to me like something might be wrong with the device itself. The checksum is what is actually ensuring that all the data is received. Failing the check that badly means that either the data is corrupted or it was missing. And since the number is always the same, it looks like there may be something wrong with the memory where this is received.

My suggestions would be to check if it might be the cable, it might be losing packets and that could lead to missing data in calculation. If not, and if the data you have on it is not yours/recent/important right now, you can zero the memory and see if that helps.

As for the script — I realized that the script is actually using Py3.6 syntax, because I didn't pay enough attention for the tooling, I'll fix that later.

**Comment by steve8x8** [comment]
Is there a means to read the event log, before I enter `$resetpatient` to clear the memory? (I suppose that's the command to use, although the event log might even survive, and there's a chance to completely break the device.)

I had used multiple cables, but cable problems would not result in missing records (as a broken cable would not make a difference between linefeeds and other bit patterns), would they? In any case, I've got confirmation from the owner to reset the device once all important stuff has been saved. And there's Glimp as a backup.

Thanks so far!

**Comment by Flameeyes** [comment]
The _events_ should still be around, but the readings will definitely be deleted with `$resetpatient` (this is wired in with the `glucometer zero` command). This is possibly version dependent so I can't make guarantees one way or the other.

The original software handles things differently with a binary protocol I never managed to figure out :(

**Comment by steve8x8** [comment]
Is there a means to read the event log, before I enter `$resetpatient` to clear the memory? (I suppose that's the command to use, although the event log might even survive, and there's a chance to completely break the device.)

I had used multiple cables, but cable problems would not result in missing records (as a broken cable would not make a difference between linefeeds and other bit patterns), would they? In any case, I've got confirmation from the owner to reset the device once all important stuff has been saved. And there's Glimp as a backup.

Thanks so far!

**Comment by steve8x8** [comment]
I gave the device a final chance - it passed both `$arresult?` and `$history?` (with a reduced set of records though) before running `$resetpatient`.
I am a bit surprised that it's a mmol/L device (as shown in the display and returned by `$uom?`) although the values presented by `$arresult?` and `$history?` undoubtedly are in mg/dL instead. Whatever that means.
I'm looking forward to using a fresh device (I won't be able to update the firmware though), and giving more than a hundred gnuplot daily diagrams to the previous owner :)
Of course, I will use `glucometerutils` to read out the new values, and report whether the issues persist. Thanks a bunch for getting me this far!

**Comment by steve8x8** [comment]
Just an additional hint at data corruption (where?):
Spotted in the history,
```
59377,12,4,20,19,23,25,29,1,0,0,0,0,97,3285,0
59373,12,4,20,19,22,53,43,1,0,15,50,18,1,0,0,0,0,77,16260,0
58985,12,4,17,19,15,20,18,1,0,0,0,0,118,16230,0
```
Obviously the reading in the middle line is non-existant, and the "77" value belongs to 2019-04-17 15:50 - three days later, the minute counter has wrapped (at 16k?). It'd be interesting to know whether strange things tend to happen at wrap-arounds (record number at 64k, minute counter at 16k, ...)

I probably shouldn't trust the device for more than 12 days. Let's see what happens at the end of the 14-day wear period (14 days ~ 20000 minutes, so there'll be a wraparound at least).
